### ISSUE TITLE
Remote network not accessible from computer using wg-server as default gateway

### ISSUE THREAD

**Issue by peterpepo** [sergibarroso/wireguard-vpn-setup#1]
# Setup
I have following setup:
- please see picture below
- home router with
  - private network 192.168.2.0/24, local ip 192.168.2.1
  - public facing ip 24.188.166.63 (just an example, not my actual ip)
- wg-server (raspberry pi, debian)
  - eth0 interface connected to local network, ip 192.168.2.42
  - wg0 tunnel with ip of 10.222.0.1/24
  - dns commented out (I want to rule this out for now)
- computer-A (windows10)
  - connected to local network, ip 192.168.2.11
  - no wireguard installed
  - default gateway set to: 192.168.2.42 (wg-server's local ip)
  - dns set to 1.1.1.1 or 192.168.2.1
- wg-client (vps, debian)
  - eth0 interface connected to public network 131.137.42.6 (example, not my actual ip)
  - wg0 tunnel, ip 10.222.0.2/24

![Untitled Diagram drawio](https://github.com/sergibarroso/wireguard-vpn-setup/assets/2683131/c0a494b6-11e3-4ad5-96b4-f39996f0e697)

The wg-server and wg-client are using exactly your configurations (with placeholders correctly replaced for eth0).

After establishing the tunnel:
- wg-server traffic seems to be correctly routed through wg-client (running these commands on wg-server)
  - `curl ifconfig.me` returns correctly `wg-client's public ip'
  - `traceroute <any_url/ip>` - i can see a hop through 10.0.0.2
  - `ping <any_public_ip/dns_name>` works correctly, I get replies
- ping from wg-server to wg-client using their tunnel ips (and vice versa) works ok

# Problem

**Now comes the problem. Nothing of mentioned above works for the computer-A connected to local network, with wg-server's local ip set as a default gateway.**
- `ping <anything>` - times out (pinging local network 192.168.2.0/24 works, dns is also correctly resolved when using 192.168.2.1 as dns)
- `tracert <any_url/ip>` - i can see a hop through 192.168.2.42, doesn't get any further - times out on next row
- `curl ifconfig.me` times out

**Please can you help me to sort this out? This is inteded use, correct?**
I expect the computer-A to route all traffic through wg-server to wg-client resulting in:
- public ip displaying my vps'es ip (wg-client)
- route all traffic through tunnel on devices, where I can't install wireguard (for whatever reason)
- route all dns queries through tunnel (ok, I probably need to install dns server on wg-client and uncomment it on wg-server side correct?)
- effectively pretending like computer-A is sitting on my vps'es network

**Comment by sergibarroso** [comment]
Hi @peterpepo 

Thanks for your interest in this repository.

From what I can see, my first guess is a problem with iptables in at least one of the wireguards.

Try to run a traceroute from the wg-server to a public IP and respond to PING (not the wg-client public IP) like `traceroute <ANY_PUBLIC_IP>`.

If the result is that you see two hops and then no answer

```shell
1 10.222.0.2 [...]
2 131.137.42.6 [...]
3 ***
```

If the traceroute stops indefinitely at point 3, then it's an iptables problem; if not, then it's something else.

If this doesn't give you enough info to solve the problem, please drop me a message, and we can continue via email.

Thanks
